baseURL = "http://example.com/"
languageCode = "en-us"
title = "JAMSpace"
theme = "minimal"

[params]
    author = "Dennis Stepp"
    description = "Your resource for bluegrass jam songs."
    githubUsername = "#"
    accent = "blue"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "solarized-dark"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/songs/"
    name = "Songs"
    weight = 2

[[menu.main]]
    url = "/festivals/"
    name = "Festivals"
    weight = 3

[[menu.main]]
    url = "/jams/"
    name = "Jams"
    weight = 4

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[menu.icon]]
    url = "mailto:me@example.com"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/username/"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "https://twitter.com/username/"
    name = "twitter"
    weight = 3

[[menu.icon]]
    url = "https://www.linkedin.com/in/username/"
    name = "linkedin"
    weight = 4

[[menu.icon]]
    url = "https://www.stackoverflow.com/username/"
    name = "stack-overflow"
    weight = 5
